# Generated by Django 6.0.3 on 2026-03-26 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 26, 16, 34, 24, 326588), verbose_name='logging time'),
        ),
    ]
