# Generated by Django 6.0.3 on 2026-03-26 14:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_meal_log_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 26, 18, 29, 16, 62870), verbose_name='logging time'),
        ),
    ]
