# Generated by Django 6.0.3 on 2026-03-26 16:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0004_alter_meal_log_date_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 26, 20, 19, 45, 983129), verbose_name='logging time'),
        ),
        migrations.CreateModel(
            name='CalorieGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField()),
                ('effective_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date'],
                'unique_together': {('user', 'effective_date')},
            },
        ),
    ]
