# Generated by Django 6.0.3 on 2026-03-26 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0005_alter_meal_log_date_caloriegoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='daily_calorie_goal',
        ),
        migrations.AlterField(
            model_name='meal',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 26, 20, 25, 54, 957362), verbose_name='logging time'),
        ),
    ]
